/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      width: {
        customW1: "20.69rem",
        customW2: "26.81rem",
        customW3: "29.3rem",
        customW4: "21.25rem",
        customW5: "9rem",
        customW6: "25.5rem",
        customW7: "39.575rem",
      },
      height: {
        customH1: "33.18rem",
      },
      padding: {
        customP1: "1.875rem",
      },
      borderRadius: {
        customRadius1: "2.5rem",
        customRadius2: "0.625rem",
      },
      fontFamily: {
        customFont: ["Inter", "Calibri", "sans-serif"],
      },
      fontSize: {
        customFS1: "2.5rem",
        customFS2: "3.125rem",
        customFS3: "1.75rem",
        customFS4: "1.875rem",
      },
      lineHeight: {
        customLH1: "3.81rem",
        customLH2: "3.75rem",
        customLH3: "3.78rem",
        customLH4: "2.1rem",
        customLH5: "1.875rem",
        customLH6: "1.36rem",
      },
      colors: {
        primary: "#54bd95",
        secondary: "#191a15",
        backup: "#a6a6a6",
        color4: "#f9f8fe",
        color5: "#a9a7b6",
        color6: "#4535af",
        color7: "#ffaa94",
        color8: "#fbc75e",
        color9: "#f8f8fa",
      },
      rotate: {
        15: "15deg",
      },
      gridTemplateRows: {
        customRows1: "auto 1fr",
      },
      gridTemplateColumns: {
        customCols1: "auto 1fr auto",
      },
    },
  },
  plugins: [],
};

// safelist: [
//   "my-0",
//   "my-1",
//   "my-6",
//   "px-customP1",
//   "h-10",
//   "h-12",
//   "w-10",
//   "w-12",
//   "w-48",
//   "w-customW1",
//   "w-customW2",
//   "w-customW3",
//   "w-customW4",
//   "rounded-lg",
//   "rounded-full",
//   "rounded-customRadius1",
//   "text-lg",
//   "text-base",
//   "text-center",
//   "text-white",
//   "text-customFS1",
//   "text-customFS2",
//   "text-customFS3",
//   "text-customFS4",
//   "leading-customLH1",
//   "leading-customLH2",
//   "leading-customLH3",
//   "leading-customLH4",
//   "leading-customLH5",
//   "leading-customLH6",
//   "bg-color6",
//   "bg-color7",
//   "bg-color8",
//   "top-8",
//   "top-44",
//   "left-4",
//   "left-20",
//   "right-0",
//   "right-12",
//   "-right-8",
//   "-right-16",
//   "bottom-0",
//   "bottom-80",
//   "-bottom-4",
//   "-bottom-7",
//   "rotate-15",
//   "-rotate-15",
//   "-rotate-12",
//   "flex-col-reverse",
//   "grid-cols-2",
//   "customCols1",
//   "gap-1",
//   "gap-4",
//   "justify-between",
// ],
